Repository ofiwg/libfabric, pull requests merged in 2018-11, with the labels that each got.

#4585 prov/sockets: Enable MSG EP when calling fi_accept
  prov/sockets/src/sock_ep_msg.c
Labels: for-1.5.x

#4584 prov/sockets: Enable MSG EP when calling fi_accept
  prov/sockets/src/sock_ep_msg.c
Labels: for-1.6.x

#4583 prov/sockets: Enable MSG EP when calling fi_accept
  prov/sockets/src/sock_ep_msg.c
Labels: for-1.5.x, for-1.6.x

#4621 prov/rxm, util: bug fixes for rxm CQ and util MR cache
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_ep.c
  prov/util/src/util_mr_cache.c
Labels: for-1.6.x
