Repository ofiwg/libfabric, pull requests merged in 2018-03, with the labels that each got.

#3880 prov/psm2: Fix incorrect application of round-robin HFI unit assignment
  prov/psm2/src/psmx2_ep.c
Labels: bug

#3897 prov/sockets: Progress all rx contexts for a scalable endpoint
  prov/sockets/include/sock.h
  prov/sockets/src/sock_cntr.c
  prov/sockets/src/sock_cq.c
  prov/sockets/src/sock_progress.c
Labels: bug

#3193 prov/sockets: new code for the connection manager for improved scalability
  include/ofi_signal.h
  prov/sockets/include/sock.h
  prov/sockets/src/sock_conn.c
  prov/sockets/src/sock_dom.c
  prov/sockets/src/sock_ep.c
  prov/sockets/src/sock_ep_msg.c
  prov/sockets/src/sock_progress.c
  prov/udp/src/udpx_ep.c
  prov/util/src/util_wait.c
  src/common.c
Labels: for-1.7.x

#3907 prov/util,rxm: optimizations
  include/ofi_util.h
  prov/rxd/src/rxd_av.c
  prov/rxm/src/rxm_domain.c
  prov/rxm/src/rxm_init.c
  prov/util/src/util_av.c
  prov/verbs/src/ep_dgram/verbs_dgram_av.c
Labels: for-1.7.x

#3919 osd/win: Fix string representation of version
  include/windows/config.h
Labels: for-1.6.x

#3929 prov/rxm: Fix read from pointer after free (cheery-pick onto v1.6.x branch)
  prov/rxm/src/rxm_ep.c
Labels: for-1.6.x

#3931 util/av: Fix handling of double insertion of the same address
  prov/util/src/util_av.c
Labels: evaluating, for-1.6.x

#3952 configure.ac: ensure that all the debug compiler flags work
  configure.ac
Labels: for-1.6.x

#3962 v1.6.x: configure.ac: ensure that all the debug compiler flags work
  configure.ac
Labels: bug

#3961 util/av: Don't check slot value if FI_SOURCE isn't set (for v1.6.x)
  prov/util/src/util_av.c
Labels: for-1.6.x

#3964 config: Remove NDEBUG for debug build (for v1.6.x)
  configure.ac
Labels: for-1.6.x

#3956 util/av: Handle the deletion of the same address multiple times (for v-1.6.x)
  include/ofi_util.h
  prov/util/src/util_av.c
Labels: for-1.6.x
