Repository ofiwg/libfabric, pull requests merged in 2018-12, with the labels that each got.

#4661 Revert "fabtests: rename files and directories to better reflect intent"
  fabtests/Makefile.am
  fabtests/Makefile.win
  fabtests/autogen.sh
  fabtests/benchmarks/benchmark_shared.c
  fabtests/benchmarks/dgram_pingpong.c
  fabtests/benchmarks/msg_bw.c
  fabtests/benchmarks/msg_pingpong.c
  fabtests/benchmarks/rdm_cntr_pingpong.c
  fabtests/benchmarks/rdm_pingpong.c
  fabtests/benchmarks/rdm_tagged_bw.c
  fabtests/benchmarks/rdm_tagged_pingpong.c
  fabtests/benchmarks/rma_bw.c
  fabtests/common/jsmn.c
  fabtests/common/osx/osd.c
  fabtests/common/shared.c
  fabtests/common/windows/getopt.c
  fabtests/common/windows/osd.c
  fabtests/fabtests.vcxproj
  fabtests/fabtests.vcxproj.filters
  fabtests/functional/av_xfer.c
  fabtests/functional/cm_data.c
  fabtests/functional/cq_data.c
  fabtests/functional/dgram.c
  fabtests/functional/dgram_waitset.c
  fabtests/functional/inj_complete.c
  fabtests/functional/mcast.c
  fabtests/functional/msg.c
  fabtests/functional/msg_epoll.c
  fabtests/functional/msg_sockets.c
  fabtests/functional/multi_ep.c
  fabtests/functional/multi_mr.c
  fabtests/functional/poll.c
  fabtests/functional/rdm.c
  fabtests/functional/rdm_atomic.c
  fabtests/functional/rdm_deferred_wq.c
  fabtests/functional/rdm_multi_domain.c
  fabtests/functional/rdm_multi_recv.c
  fabtests/functional/rdm_rma_simple.c
  fabtests/functional/rdm_rma_trigger.c
  fabtests/functional/rdm_shared_av.c
  fabtests/functional/rdm_tagged_peek.c
  fabtests/functional/recv_cancel.c
  fabtests/functional/resmgmt_test.c
  fabtests/functional/scalable_ep.c
  fabtests/functional/shared_ctx.c
  fabtests/functional/unexpected_msg.c
  fabtests/include/shared.h
  fabtests/include/unit_common.h
  fabtests/ubertest/fabtest.h
  fabtests/ubertest/uber.c
  fabtests/unit/av_test.c
  fabtests/unit/cntr_test.c
  fabtests/unit/common.c
  fabtests/unit/cq_test.c
  fabtests/unit/dom_test.c
  fabtests/unit/eq_test.c
  fabtests/unit/getinfo_test.c
  fabtests/unit/mr_test.c
  fabtests/unit/resource_freeing.c
Labels: bug

#4674 prov/gni: fix a problem with double free
  prov/gni/include/gnix_vc.h
  prov/gni/src/gnix_msg.c
  prov/gni/src/gnix_vc.c
Labels: for-1.6.x

#4680 prov/rxm: Rework locking around progress
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_atomic.c
  prov/rxm/src/rxm_conn.c
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_rma.c
Labels: for-1.7.x

#4688 prov/rxm: Don't return -FI_ENOTCONN for RDM endpoint
  prov/rxm/src/rxm.h
Labels: for-1.7.x

#4698 v1.7.0rc2
  configure.ac
Labels: ⚠️ Do not merge

#4711 v1.7.0rc3
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#4714 prov/mlx: Fix wrong fi_getname behavior
  prov/mlx/src/mlx_av.c
  prov/mlx/src/mlx_cm.c
Labels: for-1.7.x
