Repository ofiwg/libfabric, pull requests merged in 2018-05, with the labels that each got.

#4052 prov/rxm: Fix desc field when postponing RMA ops.
  prov/rxm/src/rxm_rma.c
Labels: for-1.6.x

#4087 prov/rxm: fix a bug in matching directed receives
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_ep.c
Labels: for-1.5.x, for-1.6.x

#4092 prov/rxm: update unexpected messages and re-process recvs on AV insert
  include/ofi_util.h
  prov/rxm/src/rxm_cq.c
  prov/util/src/util_av.c
Labels: bug, for-1.5.x, for-1.6.x
