Repository ofiwg/libfabric, pull requests merged in 2018-08, with the labels that each got.

#4288 prov/rxm: Improve fast path by avoiding locks in Connected case
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_rma.c
Labels: enhancement

#4301 prov/gni: Fix stale data issue with SMSG buffers
  prov/gni/src/gnix_mbox_allocator.c
  prov/gni/src/gnix_nic.c
Labels: for-1.6.x

#4309 prov/verbs, rxm: bug fixes
  prov/rxm/src/rxm_init.c
  prov/util/src/util_av.c
  prov/verbs/src/verbs_info.c
Labels: for-1.5.x, for-1.6.x

#4348 prov/sockets: Increase maximum message size
  prov/sockets/include/sock.h
Labels: for-1.6.x
