Repository ofiwg/libfabric, pull requests merged in 2019-09, with the labels that each got.

#5242 prov/rxm,core: Use FI_ORDER_RMA bits for FI_ATOMIC
  prov/rxm/src/rxm_init.c
Labels: cray-jenkins-build

#5256 prov/rxm, prov/gni, core, contrib/cray: release/1.8.x cherry pick
  contrib/cray/Jenkinsfile.verbs
  prov/gni/src/gnix_msg.c
  prov/util/src/util_buf.c
  prov/util/src/util_mr_cache.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_cm.c
  prov/verbs/src/verbs_cm_xrc.c
  prov/verbs/src/verbs_domain_xrc.c
  prov/verbs/src/verbs_eq.c
Labels: cray-jenkins-build

#5269 prov/verbs: fixes for handling IPv6 link local address, unknown CM event
  prov/verbs/src/verbs_eq.c
  prov/verbs/src/verbs_info.c
Labels: for-v1.8.x

#5289 prov/rxd: fix default av count
  prov/rxd/src/rxd.h
  prov/rxd/src/rxd_av.c
Labels: for-v1.8.x

#5300 prov/sockets: add lock to protect av table access
  prov/sockets/include/sock.h
  prov/sockets/src/sock_av.c
Labels: for-v1.8.x

#5299 core/mr_cache: Ensure that we remove the correct entry + ubertest updates
  fabtests/man/fabtests.7.md
  fabtests/scripts/runfabtests.sh
  fabtests/test_configs/eq_cq.test
  fabtests/test_configs/lat_bw.test
  fabtests/test_configs/ofi_rxd/udp.test
  fabtests/test_configs/psm/all.test
  fabtests/test_configs/psm2/all.test
  fabtests/test_configs/psm2/verify.test
  fabtests/test_configs/shm/all.test
  fabtests/test_configs/shm/quick.test
  fabtests/test_configs/shm/verify.test
  fabtests/test_configs/tcp/quick.test
  fabtests/test_configs/udp/all.test
  fabtests/test_configs/udp/functional.test
  fabtests/test_configs/udp/lat_bw.test
  fabtests/test_configs/udp/quick.test
  fabtests/test_configs/usnic/all.test
  fabtests/test_configs/usnic/quick.test
  fabtests/test_configs/verbs/all.test
  fabtests/test_configs/verbs/quick.test
  fabtests/ubertest/config.c
  fabtests/ubertest/uber.c
  include/ofi_mr.h
  include/ofi_tree.h
  prov/rxd/src/rxd_av.c
  prov/util/src/util_mr_cache.c
  prov/verbs/src/verbs_domain_xrc.c
  src/tree.c
Labels: for-v1.8.x

#5317 v1.8.1 - for CI testing only
  NEWS.md
  configure.ac
  fabtests/configure.ac
Labels: ⚠️ Do not merge
