Repository ofiwg/libfabric, pull requests merged in 2019-06, with the labels that each got.

#5068 prov/psm2: Add configuration options to disable some PSM2 features
  prov/psm2/configure.m4
  prov/psm2/src/version.h
Labels: for-1.7.x

#5076 prov/tcp: man page update
  man/fi_tcp.7.md
Labels: documentation

#5092 v1.7.2 - final release for CI testing
  NEWS.md
  configure.ac
  fabtests/configure.ac
Labels: evaluating, ⚠️ Do not merge

#5095 prov/gni: fix another issue with GNI mrecv
  prov/gni/src/gnix_msg.c
  prov/gni/test/rdm_multi_recv.c
Labels: for-1.7.x

#5120 v1.8.0rc2
  configure.ac
  fabtests/configure.ac
Labels: evaluating, ⚠️ Do not merge
