Repository ofiwg/libfabric, pull requests merged in 2020-08, with the labels that each got.

#6153 prov/efa: Add the missing op_flag FI_MULTI_RECV
  prov/efa/src/rxr/rxr_attr.c
Labels: for-1.11.x

#6152 smr: Fix compile warnings, util/sockets: Handle fi_mr_attr compatibility
  include/ofi_mr.h
  prov/shm/src/smr.h
  prov/shm/src/smr_progress.c
  prov/sockets/src/sock_mr.c
  prov/util/src/util_mr_map.c
Labels: for-1.11.x

#6130 rdma/fi_domain, src/hmem_ze: L0 support
  Makefile.am
  configure.ac
  include/ofi_hmem.h
  include/rdma/fi_domain.h
  libfabric.vcxproj
  man/fi_mr.3.md
  src/hmem.c
  src/hmem_ze.c
Labels: prerequisite PR

#6154 prov/efa: Wait handshake before using read messge protocol on GPU memory
  prov/efa/src/rxr/rxr_msg.c
Labels: for-1.11.x

#6133 prov/efa: msg_prefix and other changes
  prov/efa/src/efa_cq.c
  prov/efa/src/efa_fabric.c
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_attr.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_init.c
  prov/efa/src/rxr/rxr_msg.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_entry.c
  prov/efa/src/rxr/rxr_pkt_entry.h
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/efa/src/rxr/rxr_pkt_type_req.h
Labels: for-1.11.x

#6159 prov/efa: rxr_pkt_wait_handshake() to return -FI_EAGAIN when timeout
  prov/efa/src/rxr/rxr_pkt_cmd.c
Labels: for-1.11.x

#6160 CUDA initialization updates
  include/ofi_hmem.h
  src/hmem_cuda.c
Labels: for-1.11.x

#6161 hmem: Update ROCR HMEM init
  src/hmem_rocr.c
Labels: for-1.11.x

#6162 fi_tostr: Add FI_HMEM_ZE support
  src/fi_tostr.c
Labels: for-1.11.x

#6164 v1.11.0rc2 -- for CI
  AUTHORS
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#6163 fabtests/common: add FI_MR_HMEM
  fabtests/common/shared.c
Labels: for-1.11.x

#6166 src/hmem_ze, fabtests/hmem_ze: update to L0 v1.0 API
  fabtests/common/hmem_ze.c
  src/hmem_ze.c
Labels: for-1.11.x

#6168 prov/psm2: Treat dynamic connection errors as fatal
  prov/psm2/src/psmx2.h
  prov/psm2/src/psmx2_av.c
Labels: for-1.11.x

#6165 prov/efa: Fix FI_HMEM backwards compat
  prov/efa/src/efa_fabric.c
  prov/efa/src/efa_mr.c
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.11.x

#6170 prov/psm2: Always generate log message for fatal errors
  prov/psm2/src/psmx2_av.c
Labels: for-1.11.x

#6171 prov/shm: Fix a CMA check bug
  prov/util/src/util_shm.c
Labels: for-1.11.x

#6172 Fix reporting of FI_COLLECTIVE caps and add to getinfo_test
  fabtests/unit/getinfo_test.c
  man/fi_endpoint.3.md
  man/fi_getinfo.3.md
  prov/rxm/src/rxm_attr.c
Labels: for-1.11.x

#6184 prov/efa: ignore unsupported req packets instead write error
  prov/efa/src/rxr/rxr_pkt_cmd.c
Labels: for-1.11.x

#6179 NEWS: Update psm2 provider notes for 1.11.0
  NEWS.md
Labels: for-1.11.x

#6182 NEWS.md: add shm and core news for 1.11
  NEWS.md
Labels: for-1.11.x

#6183 NEWS.md: add EFA provider changes for 1.11.0
  NEWS.md
Labels: for-1.11.x

#6187 man/fi_mr: Document CUDA and ROCR mem monitors
  man/fi_mr.3.md
Labels: for-1.11.x

#6193 prov/efa: revert "ignore unsupported req packets instead write error"
  prov/efa/src/rxr/rxr_pkt_cmd.c
Labels: for-1.11.x

#6208 prov/verbs: Fix XRC transport shared INI QP locking
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_cm_xrc.c
  prov/verbs/src/verbs_domain_xrc.c
Labels: cray-jenkins-build

#6222 prov/verbs: Fix disablement of RQ flow control
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_ep.c
Labels: cray-jenkins-build
