Repository ofiwg/libfabric, pull requests merged in 2020-04, with the labels that each got.

#5797 prov/efa: Fix addr_format handling for RDM endpoints
  prov/efa/src/rxr/rxr_init.c
Labels: bug

#5821 util/util_attr: fix ofi_cap_mr_mode to not drop FI_MR_HMEM
  prov/util/src/util_attr.c
Labels: for-1.10.x

#5822 prov/efa: fix getinfo path to validate FI_HMEM/FI_MR_HMEM
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.10.x

#5811 prov/shm: add large message segmentation fallback protocol
  include/ofi_shm.h
  man/fi_shm.7.md
  prov/shm/src/smr.h
  prov/shm/src/smr_atomic.c
  prov/shm/src/smr_ep.c
  prov/shm/src/smr_init.c
  prov/shm/src/smr_msg.c
  prov/shm/src/smr_progress.c
  prov/shm/src/smr_rma.c
  prov/util/src/util_shm.c
Labels: for-1.10.x

#5817 prov/efa: Error handling when shm av is exhausted
  prov/efa/src/efa.h
  prov/efa/src/efa_av.c
Labels: for-1.10.x

#5825 rxm/util: A couple fixes and updates to support pollfd wait sets
  include/ofi_util.h
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
  prov/tcp/src/tcpx_conn_mgr.c
  prov/tcp/src/tcpx_ep.c
  prov/util/src/util_cq.c
  prov/util/src/util_wait.c
Labels: for-1.10.x

#5828 v1.10.0rc2
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: cray-jenkins-build, ⚠️ Do not merge

#5830 prov/efa: Fix error handling when av open fails
  prov/efa/src/efa_av.c
Labels: for-1.10.x

#5833 prov/efa: set info->ep_attr->max_raw/war/waw_size for atomic
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.10.x

#5831 prov/shm: shm space check and error handling to avoid more than SMR_MAX_PEERS insert
  include/ofi_shm.h
  prov/shm/src/smr.h
  prov/shm/src/smr_av.c
  prov/shm/src/smr_init.c
  prov/util/src/util_shm.c
Labels: for-1.10.x

#5846 prov/shm: fix locking when processing response from self
  NEWS.md
  include/ofi_shm.h
  prov/shm/src/smr_ep.c
  prov/shm/src/smr_progress.c
  prov/util/src/util_shm.c
Labels: for-1.10.x

#5854 prov/efa: Use ofi_freealign() to free conn
  prov/efa/src/efa_av.c
Labels: for-1.10.x

#5855 mrcache: Free lock when cache is not initalized
  prov/util/src/util_mr_cache.c
Labels: for-1.10.x

#5850 prov/verbs: Add check for efa_devices
  prov/verbs/src/verbs_info.c
Labels: for-1.10.x

#5858 v1.10.0rc3
  AUTHORS
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#5865 prov/efa: remove ordering bits from rxr_env
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_init.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
Labels: for-1.10.x

#5868 prov/efa: environmental variables adjustment and man page.
  man/fi_efa.7.md
  prov/efa/src/efa.h
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_init.c
  prov/efa/src/rxr/rxr_msg.c
  prov/efa/src/rxr/rxr_rma.c
Labels: for-1.10.x

#5871 v1.10.0
  NEWS.md
  configure.ac
  fabtests/COPYING
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#5810 prov/rxm: Implement support for credit based flow control
  .gitignore
  include/ofi_util.h
  include/rdma/fabric.h
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_conn.c
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_ep.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_cq.c
  prov/verbs/src/verbs_dgram_ep_msg.c
  prov/verbs/src/verbs_domain.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_msg.c
  prov/verbs/src/verbs_rma.c
Labels: for-1.11.x

#5848 sockets: Convert to mutexes. bufpool: Hugepage fallback. core: Add universe variable
  include/ofi.h
  include/ofi_mem.h
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
  prov/sockets/include/sock.h
  prov/sockets/src/sock_cq.c
  prov/sockets/src/sock_poll.c
  prov/util/src/util_av.c
  prov/util/src/util_buf.c
  src/common.c
  src/fabric.c
Labels: for-1.11.x

#5852 configure.ac: use "pax" tar format
  configure.ac
Labels: for-1.11.x
