Repository ofiwg/libfabric, pull requests merged in 2020-07, with the labels that each got.

#6049 minor provider updates to resolve klocworks issues
  prov/mrail/src/mrail_av.c
  prov/mrail/src/mrail_cq.c
  prov/psm2/src/psmx2_init.c
  prov/rxd/src/rxd_cq.c
  prov/rxm/src/rxm_av.c
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_rma.c
  prov/shm/src/smr_av.c
  prov/shm/src/smr_progress.c
  prov/sockets/src/sock_ep.c
  prov/util/src/util_av.c
  prov/util/src/util_coll.c
  prov/util/src/util_shm.c
  prov/verbs/src/verbs_cm.c
  prov/verbs/src/verbs_cm_xrc.c
  prov/verbs/src/verbs_domain_xrc.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_eq.c
  prov/verbs/src/verbs_info.c
  src/common.c
  src/fabric.c
  util/pingpong.c
Labels: cray-jenkins-build

#6070 contrib/cray: Update Jenkinsfile for ROCR support
  contrib/cray/Jenkinsfile.verbs
Labels: cray-jenkins-build

#6085 prov/efa: Revert "do not call ofi_mr_cache_flush() in efa_mr_cache_re…
  prov/efa/src/efa_mr.c
Labels: for-1.11.x

#6097 core/mr_cache: Fix initialization of multiple MMs
  prov/util/src/util_mem_monitor.c
Labels: for-1.11.x

#6105 prov/hook: Initialize iface in hook_mr_regv()
  prov/hook/src/hook_domain.c
Labels: cray-jenkins-build

#6098 contrib/cray: Add IMB tests to libfabric CI
  contrib/cray/Jenkinsfile.verbs
  contrib/cray/bats/batsgenerator.sh
  contrib/cray/bats/benchmark.template
  contrib/cray/bats/imb.bats
  contrib/cray/bats/omb.bats
Labels: cray-jenkins-build

#6114 v1.11.0rc1
  AUTHORS
  Makefile.am
  configure.ac
  fabtests/configure.ac
  include/rdma/fabric.h
  include/windows/config.h
Labels: ⚠️ Do not merge

#6092 prov/efa: Add True Support for FI_DELIVERY_COMPLETE
  prov/efa/src/efa.h
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_atomic.c
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_msg.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_cmd.h
  prov/efa/src/rxr/rxr_pkt_type.h
  prov/efa/src/rxr/rxr_pkt_type_data.c
  prov/efa/src/rxr/rxr_pkt_type_misc.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/efa/src/rxr/rxr_pkt_type_req.h
  prov/efa/src/rxr/rxr_rma.c
Labels: for-1.11.x

#6099 prov/efa: turn off FI_HMEM support when RDMA is not available
  prov/efa/src/efa.h
  prov/efa/src/efa_device.c
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.11.x

#6136 prov/efa: Bugfix for prov version
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_attr.c
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.11.x

#6142 prov/efa: Use sysfs to detect driver's ability to handle CUDA buffers
  prov/efa/src/efa_fabric.c
Labels: for-1.11.x

#6141 prov/efa: use read message protocol for all GPU memory
  prov/efa/src/rxr/rxr_msg.c
Labels: for-1.11.x

#6077 prov/util, prov/shm, prov/efa: extend hmem_ops, device MR, add shm device support
  include/ofi_hmem.h
  include/ofi_mr.h
  include/ofi_shm.h
  include/rdma/fi_domain.h
  man/fi_domain.3.md
  prov/efa/src/rxr/rxr_pkt_type_data.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/shm/src/smr.h
  prov/shm/src/smr_atomic.c
  prov/shm/src/smr_attr.c
  prov/shm/src/smr_ep.c
  prov/shm/src/smr_init.c
  prov/shm/src/smr_msg.c
  prov/shm/src/smr_progress.c
  prov/shm/src/smr_rma.c
  prov/util/src/util_mr_map.c
  src/hmem.c
  src/hmem_cuda.c
  src/hmem_rocr.c
Labels: prerequisite PR

#6144 prov/efa: Add a Function for Handshake Triggering
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_cmd.h
Labels: prerequisite PR

#6148 prov/efa: move rdma-core related initialization to init_lower_efa_prov()
  prov/efa/src/efa_fabric.c
Labels: for-1.11.x

#6137 Feature/fabtest rocr support
  fabtests/Makefile.am
  fabtests/Makefile.win
  fabtests/common/hmem.c
  fabtests/common/hmem_rocr.c
  fabtests/configure.ac
  fabtests/fabtests.vcxproj
  fabtests/fabtests.vcxproj.filters
  fabtests/include/hmem.h
Labels: prerequisite PR

#6076 Support CUDA and ROCR in fi_mr_cache_evict
  fabtests/unit/mr_cache_evict.c
Labels: dependent on other PR
