Repository ofiwg/libfabric, pull requests merged in 2020-11, with the labels that each got.

#6379 prov/verbs: GID_IDX support
  prov/verbs/src/verbs_info.c
Labels: cray-jenkins-build

#6382 Add in cudaGetDeviceCount check into cuda_hmem_init()
  include/ofi_hmem.h
  src/hmem_cuda.c
Labels: cray-jenkins-build, for-v1.12.x

#6394 fix issue #6392
  prov/tcp/src/tcpx_rma.c
Labels: for-1.10.x, for-1.11.x

#6395 prov/tcp: Fix swapping of dest_addr and cq data for RMA inject
  prov/tcp/src/tcpx_rma.c
Labels: for-1.10.x

#6396 prov/tcp: Fix swapping of dest_addr and cq data in RMA inject
  prov/tcp/src/tcpx_rma.c
Labels: for-1.11.x

#6397 verbs: Initial support for HMEM
  prov/verbs/src/fi_verbs.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_dgram_ep_msg.c
  prov/verbs/src/verbs_domain.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_info.c
  prov/verbs/src/verbs_mr.c
  prov/verbs/src/verbs_msg.c
  prov/verbs/src/verbs_rma.c
Labels: cray-jenkins-build, for-v1.12.x

#6400 core/pmem: Fix pmem instruction checks
  include/ofi.h
Labels: for-1.10.x, for-1.11.x, for-v1.12.x

#6334 prov/efa: Minor cleanups
  prov/efa/src/efa.h
  prov/efa/src/efa_domain.c
Labels: for-v1.12.x

#6390 prov/efa: Use memory registration for emulated read protocol
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/efa/src/rxr/rxr_rma.c
  prov/efa/src/rxr/rxr_rma.h
Labels: for-v1.12.x

#6255 prov/rxm: RXM HMEM discovery
  prov/rxm/src/rxm_attr.c
  prov/rxm/src/rxm_init.c
Labels: cray-jenkins-build, for-v1.12.x

#6412 prov/gni: clean up compiler warnings
  prov/gni/include/gnix_cm.h
  prov/gni/include/gnix_freelist.h
  prov/gni/src/gnix_av.c
  prov/gni/src/gnix_cm.c
  prov/gni/src/gnix_ep.c
  prov/gni/src/gnix_msg.c
  prov/gni/test/api.c
  prov/gni/test/rdm_tagged_sr.c
  prov/gni/test/vc.c
Labels: for-v1.12.x

#6410 rxm/tcp: Eliminate bounce buffers for medium message transfers
  fabtests/benchmarks/dgram_pingpong.c
  fabtests/benchmarks/msg_bw.c
  fabtests/benchmarks/msg_pingpong.c
  fabtests/benchmarks/rdm_cntr_pingpong.c
  fabtests/benchmarks/rdm_pingpong.c
  fabtests/benchmarks/rdm_tagged_bw.c
  fabtests/benchmarks/rdm_tagged_pingpong.c
  fabtests/benchmarks/rma_bw.c
  include/ofi_util.h
  man/fi_rxm.7.md
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_conn.c
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_domain.c
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
  prov/tcp/src/tcpx.h
  prov/tcp/src/tcpx_domain.c
  prov/tcp/src/tcpx_ep.c
  prov/tcp/src/tcpx_init.c
  prov/tcp/src/tcpx_progress.c
Labels: evaluating

#6205 prov/efa: FI_DELIVERY_COMPLETE Support
  prov/efa/src/efa.h
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_atomic.c
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_msg.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_cmd.h
  prov/efa/src/rxr/rxr_pkt_type.h
  prov/efa/src/rxr/rxr_pkt_type_data.c
  prov/efa/src/rxr/rxr_pkt_type_misc.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/efa/src/rxr/rxr_pkt_type_req.h
  prov/efa/src/rxr/rxr_rma.c
Labels: for-v1.12.x
