Repository ofiwg/libfabric, pull requests merged in 2020-09, with the labels that each got.

#6206 prov/verbs: Reduce overall memory footprint in a fully connected fabric
  prov/verbs/src/fi_verbs.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_cm.c
  prov/verbs/src/verbs_cm_xrc.c
  prov/verbs/src/verbs_domain.c
  prov/verbs/src/verbs_domain_xrc.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_eq.c
  prov/verbs/src/verbs_info.c
Labels: cray-jenkins-build

#6231 contrib/cray: Fix BUILD_LIBFABRIC usage.
  contrib/cray/Jenkinsfile.verbs
Labels: cray-jenkins-build

#6246 prov/rxm: Revert HMEM changes to capability bits
  prov/rxm/src/rxm_attr.c
  prov/rxm/src/rxm_init.c
Labels: evaluating

#6248 prov/rxm: Register bounce buffers with HMEM
  prov/rxm/src/rxm_ep.c
Labels: cray-jenkins-build

#6254 contrib/cray: Updating batsgenerator.sh script
  contrib/cray/bats/batsgenerator.sh
  contrib/cray/bats/benchmark.template
  contrib/cray/bats/imb.bats
Labels: cray-jenkins-build

#6264 util/mem_hooks: port Open MPI overwrite patcher and intercept logic fixes
  configure.ac
  prov/util/src/util_mem_hooks.c
Labels: for-1.11.x

#6267 [v1.11.x] prov/efa fixes for v1.11.x
  prov/efa/src/rxr/rxr_pkt_entry.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
Labels: for-1.11.x

#6268 prov/efa: Switch to memhooks monitor
  prov/efa/src/efa_domain.c
Labels: for-1.11.x

#6270 util/mem_hooks: fix error handling when obtaining page size
  prov/util/src/util_mem_hooks.c
Labels: for-1.11.x

#6265 prov/efa: use local read to copy data to GPU buffer
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_init.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_cmd.h
  prov/efa/src/rxr/rxr_pkt_entry.c
  prov/efa/src/rxr/rxr_pkt_entry.h
  prov/efa/src/rxr/rxr_pkt_type.h
  prov/efa/src/rxr/rxr_pkt_type_data.c
  prov/efa/src/rxr/rxr_pkt_type_misc.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/efa/src/rxr/rxr_read.c
  prov/efa/src/rxr/rxr_read.h
  prov/efa/src/rxr/rxr_rma.c
Labels: for-1.11.x

#6241 util_mem_monitor: Add flag to indicate whether to defer free
  include/ofi_mr.h
  include/windows/pthread.h
  prov/util/src/rocr_mem_monitor.c
  prov/util/src/util_mem_hooks.c
  prov/util/src/util_mem_monitor.c
Labels: for-1.11.x
