Repository ofiwg/libfabric, pull requests merged in 2020-12, with the labels that each got.

#6421 at this point a bunch of fixes everywhere
  fabtests/functional/multi_recv.c
  include/ofi_util.h
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_conn.c
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
  prov/shm/src/smr_comp.c
  prov/util/src/util_av.c
  prov/util/src/util_cq.c
  prov/util/src/util_eq.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_dgram_ep_msg.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_msg.c
  prov/verbs/src/verbs_rma.c
Labels: for-v1.12.x

#6451 travis: Fixup travis.yml file syntax
  .travis.yml
Labels: evaluating

#6462 v1.11.2
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#6466 src/common.c: fix a stack-buffer-overflow issue
  src/common.c
Labels: for-1.11.x
