Repository ofiwg/libfabric, pull requests merged in 2020-03, with the labels that each got.

#5711 v1.9.1: CI testing
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: evaluating, ⚠️ Do not merge

#5710 core/getinfo: Ignore invalid rx/tx caps
  man/fi_endpoint.3.md
  prov/util/src/util_attr.c
Labels: cray-jenkins-build

#4755 travis: enable address sanitizer
  .travis.yml
Labels: ⚠️ Do not merge

#5729 mr_cache: Do not hold monitor lock when allocating or registering memory
  include/ofi_mr.h
  man/fi_efa.7.md
  man/fi_mr.3.md
  prov/efa/src/efa.h
  prov/efa/src/efa_domain.c
  prov/efa/src/efa_fabric.c
  prov/efa/src/rxr/rxr_init.c
  prov/util/src/util_mem_monitor.c
  prov/util/src/util_mr_cache.c
Labels: for-1.9.x

#5781 prov/tcp: Fix missing ep-lock / list corruption
  prov/tcp/src/tcpx_cq.c
Labels: for-1.9.x
