Repository ofiwg/libfabric, pull requests merged in 2021-03, with the labels that each got.

#6598 src/hmem_ze: Fix a bug that may overwrite device handle with NULL
  src/hmem_ze.c
Labels: for-v1.12.x

#6604 prov/psm3/rv: Handle location change of rv header
  prov/psm3/configure.ac
  prov/psm3/configure.m4
  prov/psm3/psm3/psm_rndv_mod.c
  prov/psm3/psm3/psm_rndv_mod.h
Labels: for-v1.12.x

#6605 prov/psm3: Add missing RNDV_MOD ifdefs
  prov/psm3/psm3/psm_verbs_mr.h
  prov/psm3/psm3/ptl_ips/ips_proto_connect.c
Labels: for-v1.12.x

#6603 prov/rxm: Minor fixes for dynamic receive buffer handling
  prov/rxm/src/rxm_cq.c
  prov/tcp/src/tcpx.h
  prov/tcp/src/tcpx_progress.c
  src/iov.c
Labels: for-v1.12.x

#6607 configure.ac: fix behavior of gdrcopy library checking and usage
  configure.ac
  src/hmem_cuda_gdrcopy.c
Labels: for-v1.12.x

#6632 Move the nroff elves to GitHub actions
  .github/workflows/nroff-elves.yaml
  config/cron-run-all-md2nroff.pl
  config/distscript.pl
  config/md2nroff.pl
Labels: enhancement

#6641 core: Move efa provider ahead of psmX providers
  src/fabric.c
Labels: for-v1.12.x

#6650 Migrate the Nroff Elves to GitHub Actions
  .github/workflows/nroff-elves.sh
  .github/workflows/nroff-elves.yaml
  config/cron-run-all-md2nroff.pl
  config/distscript.pl
  config/md2nroff.pl
Labels: documentation, enhancement

#6657 psm3 v1.12.0 build issues
  config/fi_strip_optflags.m4
  configure.ac
  prov/psm3/Makefile.include
  prov/psm3/configure.m4
  prov/psm3/psm3/include/opa_user.h
  prov/psm3/psm3/psm_rndv_mod.c
  prov/psm3/psm3/psm_utils.c
  prov/psm3/psm3/psm_verbs_ep.c
Labels: for-v1.12.x, ⚠️ Do not merge
