Repository ofiwg/libfabric, pull requests merged in 2021-10, with the labels that each got.

#7135 [v1.13.x] prov/efa: fix the memcpy size in rxr_pkt_entry_copy
  prov/efa/src/rxr/rxr_pkt_entry.c
Labels: for-1.13.x

#7127 fi_endpoint: add a parameter to allow FI_HMEM p2p configuration
  include/rdma/fi_endpoint.h
  man/fi_endpoint.3.md
Labels: API update

#7159 v1.13.2 CI
  AUTHORS
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, for-1.13.x
