Repository ofiwg/libfabric, pull requests merged in 2021-01, with the labels that each got.

#6472 verbs/rxm: Fix overzealous setting of MR access flags
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_domain.c
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
Labels: evaluating

#6482 prov/tcp: Flush outstanding operations when disabling the EP
  prov/tcp/src/tcpx.h
  prov/tcp/src/tcpx_cq.c
  prov/tcp/src/tcpx_ep.c
  prov/tcp/src/tcpx_progress.c
  prov/tcp/src/tcpx_rma.c
  prov/tcp/src/tcpx_shared_ctx.c
Labels: evaluating, for-v1.12.x

#6495 prov/rxm: RC correction
  prov/rxm/src/rxm_cq.c
Labels: cray-jenkins-build, for-v1.12.x

#6496 prov/efa: Revert "adjust frequency of flush"
  prov/efa/src/efa_mr.c
Labels: for-v1.12.x

#6490 prov/verbs: reapply fix for off-by-one credit initialization
  prov/verbs/src/verbs_ep.c
Labels: for-v1.12.x

#6505 prov/efa: remove state check and unused state
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_pkt_type_misc.c
Labels: for-v1.12.x

#6508 prov/rxm: Call ofi_mem_fini when built as DL provider
  prov/rxm/src/rxm_init.c
Labels: for-v1.12.x

#6497 prov/shm: retry shm_open without O_EXCL if process is dead
  prov/util/src/util_shm.c
Labels: for-v1.12.x

#6498 prov/psm2: Check for Open MPI job key
  prov/psm2/src/psmx2_init.c
Labels: for-v1.12.x

#6511 prov/tcp: Use nonblocking sockets during CM message exchange
  man/fi_rxm.7.md
  prov/rxm/src/rxm_domain.c
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
  prov/tcp/src/tcpx.h
  prov/tcp/src/tcpx_conn_mgr.c
  prov/tcp/src/tcpx_ep.c
Labels: evaluating
