Repository ofiwg/libfabric, pull requests merged in 2021-06, with the labels that each got.

#6799 prov/util: Ensure dead regions are removed from MR Cache lists
  include/ofi_mr.h
  prov/util/src/util_mr_cache.c
Labels: for-1.13.x

#6815 fabtests: Set OOB socket to nonblocking in init_oob
  fabtests/common/shared.c
Labels: for-1.13.x

#6803 prov/rxm: Separate eager msg limit from receive buffer size
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_atomic.c
  prov/rxm/src/rxm_conn.c
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_domain.c
  prov/rxm/src/rxm_ep.c
  prov/rxm/src/rxm_init.c
Labels: evaluating, for-1.13.x

#6793 prov/efa: fix a bug in qp reuse
  prov/efa/src/efa.h
  prov/efa/src/efa_av.c
  prov/efa/src/efa_msg.c
  prov/efa/src/efa_rma.c
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
Labels: for-1.13.x

#6846 prov/efa: fix a performance issue caused by lazy initialization of packet pool
  prov/efa/src/efa.h
  prov/efa/src/efa_av.c
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_cq.c
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.13.x

#6856 prov/efa: fix a bug in zero copy receive
  prov/efa/src/efa.h
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_init.c
  prov/efa/src/rxr/rxr_msg.c
  prov/efa/src/rxr/rxr_pkt_cmd.c
  prov/efa/src/rxr/rxr_pkt_entry.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
  prov/efa/src/rxr/rxr_pkt_type_req.h
Labels: for-1.13.x

#6880 prov/rxm: Document valid choices for tcp_wait_obj
  prov/rxm/src/rxm_init.c
Labels: for-1.13.x

#6883 prov/psm3: Fix issues in race in send DMA path and CUDA support
  prov/psm3/psm3/psm.c
  prov/psm3/psm3/ptl_am/am_reqrep_shmem.c
  prov/psm3/psm3/ptl_ips/ips_proto.c
  prov/psm3/psm3/ptl_ips/ips_proto_expected.c
  prov/psm3/psm3/ptl_ips/ips_proto_mq.c
  prov/psm3/src/psmx3.h
  prov/psm3/src/psmx3_attr.c
Labels: for-1.13.x, prov/psm3

#6895 prov/psm3: Move psm3 intermediate files to provider directory
  prov/psm3/Makefile.include
Labels: prov/psm3

#6893 prov/verbs: Treat setting RNR as non-fatal
  prov/verbs/src/fi_verbs.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_eq.c
Labels: for-1.13.x
