Repository ofiwg/libfabric, pull requests merged in 2021-11, with the labels that each got.

#7197 hmem: disable cuda/ze IPC if p2p is disabled
  src/hmem_cuda.c
  src/hmem_ze.c
Labels: for-1.14.x

#7204 prov/efa: claim support of FI_HMEM_DEVICE_ONLY
  prov/efa/src/efa_mr.c
Labels: for-1.14.x

#7200 prov/psm3: fail FI_HMEM support if p2p is disabled
  prov/psm3/src/psmx3_attr.c
Labels: prov/psm3

#7198 prov/rxm: fail FI_HMEM support if p2p is disabled
  prov/rxm/src/rxm_init.c
Labels: for-1.14.x

#7175 prov/efa: call fi_setname on shm with actual name length
  prov/efa/src/efa_av.c
  prov/efa/src/rxr/rxr.h
  prov/efa/src/rxr/rxr_ep.c
  prov/efa/src/rxr/rxr_init.c
Labels: for-1.14.x

#7202 prov/rxm: Handle connection failures from verbs
  prov/rxm/src/rxm_conn.c
Labels: for-1.13.x, for-1.14.x

#7201 prov/verbs: fail FI_HMEM support if p2p is disabled
  prov/verbs/src/verbs_info.c
Labels: for-1.14.x

#7211 v1.14.0rc1 -- for CI
  AUTHORS
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating

#7217 prov/psm3: Add VERSION file to EXTRA_DIST
  prov/psm3/Makefile.include
Labels: prov/psm3

#7215 prov/efa: news update for 1.14 release
  NEWS.md
Labels: for-1.14.x

#7210 prov/shm: fix indentation
  prov/shm/src/smr.h
  prov/shm/src/smr_ep.c
Labels: for-1.14.x

#7221 prov/efa: disable 32 bit builds
  configure.ac
  prov/efa/configure.m4
Labels: for-1.14.x

#7219 core: Fix build warnings, mostly around printf format specifiers, in several areas
  include/ofi_util.h
  include/windows/sched.h
  libfabric.vcxproj
  libfabric.vcxproj.filters
  prov/efa/src/efa_fabric.c
  prov/psm2/src/psmx2_attr.c
  prov/psm3/src/psmx3_attr.c
  prov/psm3/src/psmx3_init.c
  prov/util/src/util_attr.c
  prov/util/src/util_shm.c
  prov/util/src/util_wait.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_info.c
Labels: for-1.14.x

#7220 prov/efa: fix two compilation issues
  prov/efa/src/efa_fabric.c
  prov/efa/src/rxr/rxr_pkt_type_req.c
Labels: for-1.14.x

#7222 prov/shm: disable FI_ATOMIC when FI_HMEM is requested
  prov/shm/src/smr_attr.c
Labels: for-1.14.x

#7214 src/hmem: extend pointer query functions
  include/ofi_hmem.h
  prov/shm/src/smr_ep.c
  prov/verbs/src/verbs_mr.c
  src/hmem.c
  src/hmem_cuda.c
  src/hmem_rocr.c
  src/hmem_ze.c
Labels: for-1.14.x

#7216 fabtests/common: add in band exchange support for device memory
  fabtests/common/shared.c
  fabtests/functional/rdm_rma_trigger.c
Labels: for-1.14.x

#7223 v1.14.0rc2 - for CI verification
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating

#7112 prov/rxm: Provide quicker response to CM progress
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_conn.c
  prov/rxm/src/rxm_cq.c
Labels: ⚠️ Do not merge, evaluating

#7232 core/rxm/verbs: Expand and cleanup log messages
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_conn.c
  prov/verbs/src/fi_verbs.c
  prov/verbs/src/fi_verbs.h
  prov/verbs/src/verbs_cm.c
  prov/verbs/src/verbs_cm_xrc.c
  prov/verbs/src/verbs_cq.c
  prov/verbs/src/verbs_dgram_av.c
  prov/verbs/src/verbs_domain.c
  prov/verbs/src/verbs_domain_xrc.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_eq.c
  prov/verbs/src/verbs_info.c
  src/log.c
Labels: for-1.14.x

#7238 prov/efa: handle queued local read request correctly
  prov/efa/src/rxr/rxr_ep.c
Labels: for-1.14.x

#7243 prov/verbs: refine vrb_mr_ofi2ibv_access
  prov/verbs/src/verbs_mr.c
Labels: for-1.14.x

#7240 core/getinfo: Fix check if provider requires use of shared contexts
  prov/netdir/src/netdir_ep_msg.c
  prov/netdir/src/netdir_ep_rma.c
  prov/netdir/src/netdir_ep_srx.c
  prov/netdir/src/netdir_init.c
  prov/util/src/util_attr.c
Labels: for-1.14.x

#7239 prov/rxm: Shutdown existing connections if we receive a new request
  prov/rxm/src/rxm_conn.c
Labels: evaluating, for-1.14.x

#7247 v1.14.0rc3 -- for CI
  AUTHORS
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating

#7253 NEWS.md: update shm for 1.14
  NEWS.md
Labels: for-1.14.x

#7250 Allow to override build date with SOURCE_DATE_EPOCH
  prov/psm3/Makefile.include
Labels: prov/psm3

#7257 core: Define XPU triggering capability
  include/rdma/fabric.h
  include/rdma/fi_endpoint.h
  include/rdma/fi_trigger.h
  man/fi_endpoint.3.md
  man/fi_getinfo.3.md
  man/fi_trigger.3.md
Labels: evaluating
