Repository ofiwg/libfabric, pull requests merged in 2021-02, with the labels that each got.

#6539 prov/rxm: prioritize credit exchange in the deferred queue
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_domain.c
Labels: for-1.11.x

#6545 prov/rxm: first set of changes to fix up completion error handling
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_ep.c
Labels: for-1.11.x, for-v1.12.x

#6551 prov/rxm: More cleanups in completion handling code paths
  prov/rxm/src/rxm_cq.c
Labels: for-v1.12.x

#6557 fabtests: Fix unexpected msg test to actually test unexpected msgs
  fabtests/functional/unexpected_msg.c
Labels: for-v1.12.x

#6575 prov/psm3: Disable psm3 provider if with-psm2-src is used
  prov/psm3/configure.m4
Labels: for-v1.12.x

#6546 prov/efa: exclude EFA when FI_HMEM and FI_LOCAL_COMM are selected
  prov/efa/src/rxr/rxr_init.c
Labels: for-v1.12.x

#6574 ci/travis: Add psm3 to Travis CI
  .travis.yml
Labels: for-v1.12.x

#6567 hmem: Fix rocr_is_addr_valid() check for AMD GPU memory
  src/hmem_rocr.c
Labels: cray-jenkins-build

#6588 prov/psm3: Add missing ifdefs for rv module
  prov/psm3/psm3/psm_ep.c
  prov/psm3/psm3/psm_hal_gen1/psm_gdrcpy.c
  prov/psm3/psm3/ptl_ips/ips_expected_proto.h
Labels: for-v1.12.x

#6596 prov/psm3: remove warning from linking objects
  prov/psm3/Makefile.include
Labels: for-v1.12.x

#6600 prov/psm3: update psm3 to use upstream RV ABI
  prov/psm3/configure.ac
  prov/psm3/configure.m4
  prov/psm3/psm3/psm.c
  prov/psm3/psm3/psm_ep.c
  prov/psm3/psm3/psm_hal_gen1/psm_gdrcpy.c
  prov/psm3/psm3/psm_rndv_mod.c
  prov/psm3/psm3/psm_rndv_mod.h
  prov/psm3/psm3/psm_stats.c
  prov/psm3/psm3/psm_stats.h
  prov/psm3/psm3/psm_utils.c
  prov/psm3/psm3/psm_utils.h
  prov/psm3/psm3/psm_verbs_ep.c
  prov/psm3/psm3/psm_verbs_ep.h
  prov/psm3/psm3/psm_verbs_mr.c
  prov/psm3/psm3/psm_verbs_mr.h
  prov/psm3/psm3/ptl_ips/ips_expected_proto.h
  prov/psm3/psm3/ptl_ips/ips_path_rec.c
  prov/psm3/psm3/ptl_ips/ips_path_rec.h
  prov/psm3/psm3/ptl_ips/ips_proto.c
  prov/psm3/psm3/ptl_ips/ips_proto.h
  prov/psm3/psm3/ptl_ips/ips_proto_connect.c
  prov/psm3/psm3/ptl_ips/ips_proto_expected.c
  prov/psm3/psm3/ptl_ips/ips_proto_recv.c
  prov/psm3/psm3/ptl_ips/ips_recvhdrq.c
  prov/psm3/psm3/ptl_ips/ptl.c
  prov/psm3/psm3/ptl_ips/ptl_rcvthread.c
Labels: for-v1.12.x

#6597 prov/sockets: reset rx_ctx->progress_start when an entry is removed
  prov/sockets/src/sock_progress.c
Labels: for-v1.12.x
