Repository ofiwg/libfabric, pull requests merged in 2021-09, with the labels that each got.

#7082 core/api: Add support for rate limited log output
  include/ofi_abi.h
  include/rdma/providers/fi_log.h
  libfabric.map.in
  man/fabric.7.md
  man/fi_provider.3.md
  prov/tcp/src/tcpx_conn_mgr.c
  src/fabric.c
  src/log.c
Labels: API update

#7091 prov/rxm: Fix multi-threaded access to AV structures
  prov/rxm/src/rxm.h
  prov/rxm/src/rxm_av.c
  prov/rxm/src/rxm_conn.c
  prov/verbs/src/verbs_cm.c
  prov/verbs/src/verbs_ep.c
Labels: ⚠️ Do not merge, evaluating

#7063 prov/util: Add state lock for mem monitors start/stop
  include/ofi_mr.h
  prov/util/src/util_mem_monitor.c
Labels: bug

#7106 [v1.13.x] prov/efa: copy unexpected messages out of pre-posted shm buffers
  prov/efa/src/rxr/rxr_pkt_entry.c
  prov/efa/src/rxr/rxr_pkt_entry.h
Labels: for-1.13.x
