Repository ofiwg/libfabric, pull requests merged in 2021-04, with the labels that each got.

#6674 v1.12.1- for CI validation
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#6673 [v1.12.x] configure, fabtests/configure: cherry pick with-ze configure fixes
  configure.ac
  fabtests/common/hmem_ze.c
  fabtests/configure.ac
  src/hmem_ze.c
Labels: for-v1.12.x

#6711 tcp + rxm
  include/ofi_net.h
  prov/rxm/src/rxm_cq.c
  prov/rxm/src/rxm_init.c
  prov/tcp/src/tcpx.h
  prov/tcp/src/tcpx_comm.c
  prov/tcp/src/tcpx_conn_mgr.c
  prov/tcp/src/tcpx_cq.c
  prov/tcp/src/tcpx_ep.c
  prov/tcp/src/tcpx_init.c
  prov/tcp/src/tcpx_progress.c
  prov/util/src/util_wait.c
  src/common.c
Labels: evaluating

#6716 prov/tcp: rework the data code paths
  include/ofi_net.h
  prov/tcp/src/tcpx.h
  prov/tcp/src/tcpx_comm.c
  prov/tcp/src/tcpx_cq.c
  prov/tcp/src/tcpx_ep.c
  prov/tcp/src/tcpx_msg.c
  prov/tcp/src/tcpx_progress.c
  prov/tcp/src/tcpx_rma.c
  prov/tcp/src/tcpx_shared_ctx.c
  src/common.c
Labels: evaluating, ⚠️ Do not merge
