Repository ofiwg/libfabric, pull requests merged in 2022-03, with the labels that each got.

#7487 prov/shm: Remove broken support for 128-bit atomics
  prov/shm/src/smr_atomic.c
Labels: for-1.14.x, for-1.15.x

#7510 prov/shm: fix 0 byte SAR read
  prov/shm/src/smr_progress.c
Labels: for-1.14.x, for-1.15.x

#7512 man/fi_domain: fix small linking typo
  man/fi_domain.3.md
Labels: for-1.15.x

#7511 prov/shm: Avoid uninitialized variable with invalid atomic parameters
  prov/shm/src/smr_atomic.c
Labels: for-1.15.x

#7513 hmem_ze: Add runtime option to choose specific copy engine
  src/hmem_ze.c
Labels: for-1.15.x

#7519 configure: Replace AC_HELP_STRING with AS_HELP_STRING
  fabtests/configure.ac
Labels: for-1.15.x

#7517 cherry picked updates for v1.15.x
  man/fi_domain.3.md
  prov/shm/src/smr_atomic.c
  prov/shm/src/smr_progress.c
  src/hmem_ze.c
Labels: for-1.15.x

#7514 fabtests: Add sockets.exclude to Makefile.am
  fabtests/Makefile.am
Labels: for-1.15.x

#7515 [v1.14.x] prov/shm: fix 0 byte SAR read
  prov/shm/src/smr_progress.c
Labels: for-1.14.x

#7532 psm3: fix typo in configure.m4
  prov/psm3/configure.m4
Labels: prov/psm3, for-1.15.x

#7531 news: updated for psm3 provider
  NEWS.md
Labels: documentation, prov/psm3, for-1.15.x

#7545 hmem_ze, fabtests: Increase the number of supported ZE devices
  fabtests/common/hmem_ze.c
  include/ofi_hmem.h
Labels: for-1.14.x, for-1.15.x

#7554 osd/windows: PTHREAD_MUTEX_INITIALIZER
  prov/util/src/util_mem_monitor.c
Labels: for-1.15.x

#7523 fabtest/rdm_stress: Add stress test for RDM endpoints
  fabtests/Makefile.am
  fabtests/common/shared.c
  fabtests/configure.ac
  fabtests/functional/rdm_stress.c
  fabtests/include/shared.h
  fabtests/man/fabtests.7.md
  fabtests/man/man1/fi_rdm_stress.1
  prov/rxm/src/rxm_av.c
  prov/util/src/util_av.c
Labels: fabtests/CI

#7583 prov/opx: Correctly disable OPX if unsupported.
  prov/opx/configure.m4
Labels: for-1.15.x

#7615 news: updated for psm3 provider
  NEWS.md
Labels: for-1.15.x

#7634 man: add description of `neuron`.
  man/fi_mr.3.md
Labels: for-1.15.x
