Repository ofiwg/libfabric, pull requests merged in 2022-05, with the labels that each got.

#7732 prov/verbs: Fix a memory leak in vrb_get_sib()
  prov/verbs/src/verbs_info.c
Labels: for-1.15.x

#7734 core/pollfds: Fix windows ofi_pollfds_do_del()
  src/windows/osd.c
Labels: for-1.15.x

#7737 prov/psm3: Add missing files to make dist tarball
  Makefile.am
  prov/psm3/Makefile.include
Labels: prov/psm3, for-1.15.x

#7791 prov/verbs: Fix incorrect length used in memory registration
  prov/verbs/src/verbs_mr.c
Labels: for-1.14.x, for-1.15.x
