Repository ofiwg/libfabric, pull requests merged in 2022-04, with the labels that each got.

#7635 fabric: Introduce peer provider CQ and SRX
  Makefile.am
  include/rdma/fabric.h
  include/rdma/fi_ext.h
  man/fi_peer.3.md
  man/fi_provider.3.md
  man/man3/fi_peer.3
Labels: ABI change, API update, evaluating, work in progress

#7666 prov/opx: Disable if no compiler atomics
  prov/opx/configure.m4
Labels: for-1.15.x

#7665 Fix inline assembly for the Nvidia HPC compilers
  include/ofi_abi.h
Labels: for-1.14.x, for-1.15.x

#7667 man: Update OPX man page with new default settings
  man/fi_opx.7.md
  man/man7/fi_opx.7
Labels: for-1.15.x

#7664 core/pollfds: Use a compact pollfd array
  include/ofi_epoll.h
  src/common.c
  src/unix/osd.c
  src/windows/osd.c
Labels: evaluating, for-1.14.x, for-1.15.x

#7690 v1.14.1 -- moving to final release
  AUTHORS
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#7629 fabtests/multi_ep, prov/util, prov/verbs: separate EP resources and reenable multi EP testing
  fabtests/common/shared.c
  fabtests/component/sock_test
  fabtests/functional/multi_ep.c
  fabtests/functional/scalable_ep.c
  fabtests/functional/shared_ctx.c
  fabtests/include/shared.h
  fabtests/multinode/src/core.c
  fabtests/multinode/src/core_coll.c
  fabtests/scripts/runfabtests.sh
  fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
  fabtests/unit/av_test.c
  include/ofi_net.h
  include/ofi_util.h
  prov/util/src/util_attr.c
  prov/util/src/util_av.c
  prov/util/src/util_main.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_info.c
Labels: for-1.15.x

#7719 prov/opx: Do not return opx as a provider on systems without hardware
  prov/opx/include/opa_service.h
  prov/opx/src/fi_opx_init.c
  prov/opx/src/fi_opx_service.c
Labels: for-1.15.x

#7714 prov/rxm: Fix possible use of event data after free
  prov/rxm/src/rxm_conn.c
Labels: for-1.15.x
