Repository ofiwg/libfabric, pull requests merged in 2023-08, with the labels that each got.

#9179 v1.19.0rc1
  AUTHORS
  COPYING
  Makefile.am
  NEWS.md
  configure.ac
  fabtests/AUTHORS
  fabtests/COPYING
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating

#9200 prov/efa: Use correct tx/rx op_flags for shm
  prov/efa/src/efa_shm.c
  prov/efa/test/efa_unit_test_common.c
  prov/efa/test/efa_unit_test_info.c
Labels: for-1.19.x

#9220 v1.18.2rc1
  AUTHORS
  Makefile.am
  configure.ac
  fabtests/configure.ac
  include/rdma/fabric.h
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating

#9232 prov/verbs: Fix memory leak when creating EQ with unsupported wait object
  prov/verbs/src/verbs_eq.c
Labels: for-1.18.x, for-1.19.x

#8950 prov/psm3: add missing `FI_REMOTE_CQ_DATA` for `fi_inject_writedata`
  prov/psm3/src/psmx3_rma.c
Labels: prov/psm3
