Repository ofiwg/libfabric, pull requests merged in 2023-06, with the labels that each got.

#8909 prov/verbs: Remove saved_wc_list and use CQ directly
  prov/verbs/src/verbs_cq.c
  prov/verbs/src/verbs_ep.c
  prov/verbs/src/verbs_ofi.h
Labels: ⚠️ Do not merge, work in progress

#9036 v1.18.1rc1
  AUTHORS
  Makefile.am
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/rdma/fabric.h
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating, for-1.18.x

#9080 [v1.18.x] prov/efa: increase default shm_av_size to 256
  prov/efa/src/rdm/rxr_env.c
Labels: for-1.18.x

#9077 v1.18.x
  COPYING
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating
