Repository ofiwg/libfabric, pull requests merged in 2023-03, with the labels that each got.

#8609 v1.17.1
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge, evaluating, for-1.17.x

#8644 prov/ucx: Fix a typo in the configure script
  prov/ucx/configure.m4
Labels: for-1.18.x

#8671 prov/shm: fix potential deadlock in smr_generic_rma()
  prov/shm/src/smr_rma.c
Labels: for-1.18.x

#8674 prov/efa: fix coverity defects
  prov/efa/src/rdm/rxr_ep.h
Labels: for-1.18.x

#8669 v1.18.0r1
  AUTHORS
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
  src/fabric.c
Labels: ⚠️ Do not merge, evaluating

#8677 prov/efa: allow gdrcopy to be used when available
  prov/efa/src/rdm/rxr_pkt_type_base.c
Labels: for-1.18.x

#8676 prov/efa: fix wrong mocked return of ibv_wc_read_slid() in unit test
  prov/efa/src/rdm/rxr_ep.c
  prov/efa/src/rdm/rxr_ep.h
  prov/efa/test/efa_unit_test_ep.c
Labels: for-1.18.x

#8689 prov/efa: add assignment to optlen in rxr_ep_getopt()
  prov/efa/src/rdm/rxr_ep.c
Labels: for-1.18.x

#8697 prov/efa: fix switch case fallthrough
  prov/efa/src/rdm/rxr_ep.c
Labels: for-1.18.x

#8612 prov/efa: enrich error messages with debug and connection info
  fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
  prov/efa/Makefile.include
  prov/efa/src/dgram/efa_dgram_cq.c
  prov/efa/src/efa_errno.h
  prov/efa/src/efa_strerror.c
  prov/efa/src/rdm/efa_rdm_cq.c
  prov/efa/src/rdm/efa_rdm_error.h
  prov/efa/src/rdm/rxr.h
  prov/efa/src/rdm/rxr_ep.h
  prov/efa/src/rdm/rxr_op_entry.c
  prov/efa/src/rdm/rxr_pkt_cmd.c
  prov/efa/test/efa_unit_test_cq.c
  prov/efa/test/efa_unit_tests.c
  prov/efa/test/efa_unit_tests.h
Labels: for-1.18.x

#8719 prov/psm3: update provider to sync with IEFS 11.4.1.1.2
  prov/psm3/VERSION
  prov/psm3/debian/changelog
  prov/psm3/psm3/hal_sockets/sockets_ep.c
  prov/psm3/psm3/hal_sockets/sockets_ep.h
  prov/psm3/psm3/hal_sockets/sockets_gdrcpy.c
  prov/psm3/psm3/hal_sockets/sockets_hal.h
  prov/psm3/psm3/hal_sockets/sockets_hal_inline_i.h
  prov/psm3/psm3/hal_sockets/sockets_recvhdrq.c
  prov/psm3/psm3/hal_sockets/sockets_spio.c
  prov/psm3/psm3/hal_verbs/verbs_gdrcpy.c
  prov/psm3/psm3/psm_netutils.h
  prov/psm3/psm3/psm_utils.c
  prov/psm3/psm3/psm_utils.h
  prov/psm3/psm3/psm_verbs_mr.c
  prov/psm3/psm3/ptl_ips/ips_config.h
  prov/psm3/psm3/ptl_ips/ips_proto.c
  prov/psm3/psm3/ptl_ips/ips_proto.h
  prov/psm3/psm3/ptl_ips/ips_proto_dump.c
  prov/psm3/psm3/utils/utils_debug.c
  prov/psm3/psm3/utils/utils_dsa.c
Labels: for-1.18.x

#8722 prov/efa: adopt to rdma-core API adjustment
  prov/efa/src/efa_base_ep.c
Labels: for-1.18.x

#8728 prov/efa: adjust efa_base_ep_support_op_in_order_aligned_128_bytes()
  prov/efa/src/efa_base_ep.c
Labels: for-1.18.x

#8737 man/fi_efa: add write-once guarantee for IN_ORDER_ALIGNED_128 flags
  man/fi_efa.7.md
Labels: for-1.18.x

#8733 prov/ucx: Publish FI_LOCAL_COMM and FI_REMOTE_COMM capabilities
  prov/ucx/src/ucx.h
  prov/ucx/src/ucx_init.c
Labels: for-1.18.x
