Repository ofiwg/libfabric, pull requests merged in 2024-07, with the labels that each got.

#10172 v1.22.0rc1
  AUTHORS
  Makefile.am
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/rdma/fabric.h
  include/windows/config.h
Labels: ⚠️ Do not merge

#10175 Revert "prov/efa: refactor hmem interface initialization"
  prov/efa/Makefile.include
  prov/efa/configure.m4
  prov/efa/src/efa_domain.c
  prov/efa/src/efa_env.c
  prov/efa/src/efa_env.h
  prov/efa/src/efa_hmem.c
  prov/efa/src/efa_hmem.h
  prov/efa/src/efa_mr.c
  prov/efa/test/efa_unit_test_hmem.c
  prov/efa/test/efa_unit_test_mocks.c
  prov/efa/test/efa_unit_test_mocks.h
  prov/efa/test/efa_unit_tests.c
  prov/efa/test/efa_unit_tests.h
Labels: for-1.22.x

#10170 prov/shm: coverity fixes
  prov/shm/src/smr_progress.c
Labels: for-1.22.x

#10177 contrib/intel/jenkins: Minor Pipeline bugfixes
  contrib/intel/jenkins/Jenkinsfile
Labels: for-1.21.x, for-1.22.x

#10157 prov/verbs: Flush CQ for SQ on no SQ credit
  prov/verbs/src/verbs_ep.c
Labels: for-1.22.x

#10188 prov/efa: Add more tracepoints
  prov/efa/src/rdm/efa_rdm_ope.c
  prov/efa/src/rdm/efa_rdm_pke.c
  prov/efa/src/rdm/efa_rdm_pke_cmd.c
  prov/efa/src/rdm/efa_rdm_pke_nonreq.c
  prov/efa/src/rdm/efa_rdm_pke_rtm.c
  prov/efa/src/rdm/efa_rdm_pke_utils.c
  prov/efa/src/rdm/efa_rdm_tracepoint_def.h
Labels: for-1.22.x

#10215 prov/efa: Handle recv cancel for zero-copy recv
  prov/efa/src/rdm/efa_rdm_ep.h
  prov/efa/src/rdm/efa_rdm_ep_fiops.c
  prov/efa/src/rdm/efa_rdm_ep_utils.c
  prov/efa/src/rdm/efa_rdm_ope.h
  prov/efa/src/rdm/efa_rdm_pke.h
  prov/efa/src/rdm/efa_rdm_pke_cmd.c
  prov/efa/test/efa_unit_test_ep.c
  prov/efa/test/efa_unit_tests.c
  prov/efa/test/efa_unit_tests.h
Labels: for-1.22.x
