Repository ofiwg/libfabric, pull requests merged in 2025-06, with the labels that each got.

#11092 [v1.22.x] prov/cxi: decouple existence CXI_MAP_IOVA_ALLOC for build
  prov/cxi/include/cxip.h
Labels: for-1.22.x

#11107 v2.2.0rc1
  AUTHORS
  Makefile.am
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/rdma/fabric.h
  include/windows/config.h
  man/fi_provider.7.md
Labels: ⚠️ Do not merge

#11120 [v2.2.x] prov/cxi: Support libfabric 2.2 API
  prov/cxi/include/cxip.h
Labels: for-2.2.x

#11166 v2.2.0rc2
  AUTHORS
  NEWS.md
  configure.ac
  fabtests/configure.ac
  include/windows/config.h
Labels: ⚠️ Do not merge

#11172 [v2.2.x] prov/psm3: Update psm3 to match IEFS 12.1.0.0 release
  prov/psm3/Makefile.am
  prov/psm3/VERSION
  prov/psm3/configure.ac
  prov/psm3/configure.m4
  prov/psm3/debian/changelog
  prov/psm3/psm3/gpu/psm_gpu_cuda.c
  prov/psm3/psm3/gpu/psm_gpu_oneapi_ze.c
  prov/psm3/psm3/hal_sockets/sockets_hal.c
  prov/psm3/psm3/hal_sockets/sockets_hal_inline_i.h
  prov/psm3/psm3/hal_sockets/sockets_proto.c
  prov/psm3/psm3/hal_verbs/verbs_ep.c
  prov/psm3/psm3/hal_verbs/verbs_ep.h
  prov/psm3/psm3/hal_verbs/verbs_hal.c
  prov/psm3/psm3/hal_verbs/verbs_hal_inline_i.h
  prov/psm3/psm3/hal_verbs/verbs_rcvthread.c
  prov/psm3/psm3/hal_verbs/verbs_recvhdrq.c
  prov/psm3/psm3/hal_verbs/verbs_spio.c
  prov/psm3/psm3/include/psm3_rbtree.c
  prov/psm3/psm3/psm.c
  prov/psm3/psm3/psm2.h
  prov/psm3/psm3/psm2_hal.c
  prov/psm3/psm3/psm2_hal.h
  prov/psm3/psm3/psm2_hal_inline_t.h
  prov/psm3/psm3/psm2_hal_loopback.c
  prov/psm3/psm3/psm_config.h
  prov/psm3/psm3/psm_context.c
  prov/psm3/psm3/psm_ep.c
  prov/psm3/psm3/psm_ep.h
  prov/psm3/psm3/psm_ep_connect.c
  prov/psm3/psm3/psm_error.c
  prov/psm3/psm3/psm_help.h
  prov/psm3/psm3/psm_mpool.c
  prov/psm3/psm3/psm_mpool.h
  prov/psm3/psm3/psm_rndv_mod.c
  prov/psm3/psm3/psm_rndv_mod.h
  prov/psm3/psm3/psm_uffd.c
  prov/psm3/psm3/psm_user.h
  prov/psm3/psm3/psm_utils.h
  prov/psm3/psm3/psm_verbs_mr.c
  prov/psm3/psm3/ptl_am/am_reqrep_shmem.c
  prov/psm3/psm3/ptl_ips/ips_config.h
  prov/psm3/psm3/ptl_ips/ips_expected_proto.h
  prov/psm3/psm3/ptl_ips/ips_proto.c
  prov/psm3/psm3/ptl_ips/ips_proto.h
  prov/psm3/psm3/ptl_ips/ips_proto_am.c
  prov/psm3/psm3/ptl_ips/ips_proto_connect.c
  prov/psm3/psm3/ptl_ips/ips_proto_connect.h
  prov/psm3/psm3/ptl_ips/ips_proto_expected.c
  prov/psm3/psm3/ptl_ips/ips_proto_help.h
  prov/psm3/psm3/ptl_ips/ips_proto_mq.c
  prov/psm3/psm3/ptl_ips/ips_proto_params.h
  prov/psm3/psm3/ptl_ips/ips_proto_recv.c
  prov/psm3/psm3/ptl_ips/ips_scb.c
  prov/psm3/psm3/ptl_ips/ips_scb.h
  prov/psm3/psm3/ptl_ips/ptl.c
Labels: for-2.2.x
